[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bincode = { version = "2.0.1" }
tinyaudio = "1.1.0"
whisper-rs = { version = "0.14.3", features = ["tracing_backend"] }
