[package]
name = "native"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
whisper-rs = { version = "0.14.3", features = ["tracing_backend"] }

[dev-dependencies]
hound = "3.5.1"
