[package]
name = "rust_lib_virgil"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
ffi = "0.1.1"
flutter_rust_bridge = "=2.11.1"
whisper-rs = "0.14.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
